### ISSUE TITLE
Can't send message

### ISSUE THREAD

**Issue by BlindingDark** [termoose/nkn_client#1]
I tried to send a message to another address but did not receive the message.
But can receive messages from other address.

**Comment by termoose** [comment]
Thanks for letting me know, this project has taken a low priority for me but will get back to maintaining it soon. My guess is that the protobuf format has changed, but will take a look to make sure

**Comment by BlindingDark** [comment]
@termoose 
#2 
I updated the unencrypted message sending formats. Encrypted messages and some other functions are still being implemented and haven't add tests.

**Comment by termoose** [comment]
Nice improvement with Jason as well! Do you plan on using it for an Elixir application? I'll try to get around to implementing the end-to-end encryption soon. Do you want to add anything else to the MR or should I got ahead and merge it?

**Comment by BlindingDark** [comment]
Yes, I am trying to apply it in a chat application, like d-chat.
I think this PR contains enough commits. If there are new changes, I will open a new PR to make it easier to review.
